name: 09-glucovision-food-recognition-service CI/CD

on:
  push:
    paths:
      - '09-glucovision-food-recognition-service/**'
      - '.github/workflows/09-glucovision-food-recognition-service-ci.yml'
  pull_request:
    paths:
      - '09-glucovision-food-recognition-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push (Dry Run)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: glucovision/09-glucovision-food-recognition-service:test
